FurnitureApplication.web/Controllers/DetailController.cs
using FurnitureApplication.Services;
using FurnitureApplication.web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    public class DetailController : Controller
    {
        // GET: Detail
        [HttpGet]
        public ActionResult Details(int ID)
        {
            ProductViewModel model = new ProductViewModel();

            model.Product = ProductsServices.Instance.GetProduct(ID);

            return View(model);
        }
    }
}

FurnitureApplication.web/Controllers/Shop1Controller.cs
using FurnitureApplication.Entities;
using FurnitureApplication.Services;
using FurnitureApplication.web.Models;
using FurnitureApplication.web.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    public class Shop1Controller : Controller
    {


        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult CheckoutDetail()
        {
            CheckoutViewModel model = new CheckoutViewModel();

            var CartProductsCookie = Request.Cookies["CartProducts"];

            if (CartProductsCookie != null && !string.IsNullOrEmpty(CartProductsCookie.Value))
            {
                model.CartProductIDs = CartProductsCookie.Value.Split('-').Select(x => int.Parse(x)).ToList();

                model.CartProducts = ProductsServices.Instance.GetProducts(model.CartProductIDs);

                model.User = UserManager.FindById(User.Identity.GetUserId());

            }

            return View(model);
        }
        public ActionResult Index(string searchTerm, int? minimumPrice, int? maximumPrice, int? categoryID, int? sortBy, int? pageNo)
        {
            var pageSize = ConfigurationsService.Instance.ShopPageSize();

            ShopViewModel model = new ShopViewModel();
            model.SearchTerm = searchTerm;
            model.FeaturedCategories = CategoriesServices.Instance.GetFeaturedCategories();
            model.MaximumPrice = ProductsServices.Instance.GetMaximumPrice();

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.SortBy = sortBy;
            model.CategoryID = categoryID;

            int totalCount = ProductsServices.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy);
            model.Products = ProductsServices.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy, pageNo.Value, pageSize);
            
            model.Pager = new Pager(totalCount, pageNo, pageSize);
            return View(model);

        }
        public ActionResult FilterProducts(string searchTerm, int? minimumPrice, int? maximumPrice, int? categoryID, int? sortBy, int? pageNo)
        {
            var pageSize = ConfigurationsService.Instance.ShopPageSize();

            FilterProductsViewModel model = new FilterProductsViewModel();
            model.SearchTerm = searchTerm;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.SortBy = sortBy;
            model.CategoryID = categoryID;

            int totalCount = ProductsServices.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy);
            model.Products = ProductsServices.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy, pageNo.Value, pageSize);
            

            model.Pager = new Pager(totalCount, pageNo, pageSize);

            return PartialView(model);
        }
        [Authorize]
        public ActionResult Checkout()
        {
            CheckoutViewModel model = new CheckoutViewModel();

            var CartProductsCookie = Request.Cookies["CartProducts"];

            if(CartProductsCookie != null && !string.IsNullOrEmpty(CartProductsCookie.Value))
            {
                model.CartProductIDs = CartProductsCookie.Value.Split('-').Select(x => int.Parse(x)).ToList();

                model.CartProducts = ProductsServices.Instance.GetProducts(model.CartProductIDs);

                model.User = UserManager.FindById(User.Identity.GetUserId());

            }

            return View(model);
        }
        public JsonResult PlaceOrder(CheckoutViewModel model, string productIDs)
        {
            model.User = UserManager.FindById(User.Identity.GetUserId());
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            if (!string.IsNullOrEmpty(productIDs))
            {
                var productQuantities = productIDs.Split('-').Select(x => int.Parse(x)).ToList();
                var boughtProducts = ProductsServices.Instance.GetProducts(productQuantities.Distinct().ToList());

                Order newOrder = new Order();
                newOrder.UserID = User.Identity.GetUserId();
                newOrder.orderedAt = DateTime.Now;
                newOrder.status = "Pending";
                newOrder.TotalAmount = boughtProducts.Sum(x => x.Price * productQuantities.Where(productID => productID == x.ID).Count());

                newOrder.OrderItems = new List<OrderItem>();
                newOrder.OrderItems.AddRange(boughtProducts.Select(x => new OrderItem() { ProductID = x.ID, Quantity = productQuantities.Where(productID => productID == x.ID).Count() }));

           
                var rowsEffected = ShopService.Instance.SaveOrder(newOrder);
                result.Data = new { Success = true, Rows = rowsEffected };

                //*********Email sending code

                var fromEmail = new MailAddress("rastgroup1@gmail.com", "Rast Group");
                var toEmail = new MailAddress(model.User.Email);
                var fromEmailPassword = "ayaz123456"; //replace with actual Password

                string subject = "Order";
                string body = "Your Order Placed successfully";
                
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
                };
                using (var message = new MailMessage(fromEmail, toEmail)
                {

                    Subject = subject,
                    Body = body,
                    IsBodyHtml = true
                })
                    smtp.Send(message);
            }
            else
            {
                result.Data = new { Success = false };
            }
            return result;
        }
    }
}

FurnitureApplication.web/Views/Shop1/CheckoutDetail.cshtml
@model CheckoutViewModel

@if (Model != null && Model.CartProducts != null && Model.CartProducts.Count > 0)
{
    <div id="main">
        <div class="main-holder">
            <div class="container" style="margin-top: 130px; margin-bottom: 30px;">
                <div class="heading-area">
                    <h2>Print Order Detail</h2>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="mb-3">Billing address</h4>
                        <form class="needs-validation" novalidate="">
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <strong>Name: </strong>
                                    <span>@Model.User.Name</span>
                                </div>
                            </div>
                            <div class="mb-3">
                                <strong>Email: </strong>
                                <span>@Model.User.Email</span>
                            </div>

                            <div class="mb-3">
                                <strong>Address: </strong>
                                <span>@Model.User.Address</span>
                            </div>

                        </form>
                    </div>
                    <div class="col-md-12 mb-4">
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                            <span class="text-muted">Your cart</span>
                            <span class="badge badge-secondary badge-pill">@Model.CartProducts.Count</span>
                        </h4>
                        <ul class="list-group mb-3">
                            @foreach (var product in Model.CartProducts)
                            {
                                var productQuanitity = Model.CartProductIDs.Where(productID => productID == product.ID).Count();

                                <li class="list-group-item">
                                    <div class="clearfix" style="overflow: hidden; margin-bottom: 10px;">
                                        <span class="quanitity"><b>Total Quantity:</b> @productQuanitity</span>
                                    </div>
                                    <div>
                                        <div style="float: left; width: 60%;">
                                            <h6 class="my-0">@product.Name</h6>
                                            <small class="text-muted">@(product.Description.Length > 50 ? product.Description.Substring(0, 49) : product.Description)...</small>
                                        </div>
                                        <span class="text-muted float-right">$@product.Price</span>
                                    </div>
                                </li>
                            }

                            <li class="list-group-item d-flex justify-content-between">
                                <span>Total (USD)</span>
                                <strong>$ @Model.CartProducts.Sum(x => x.Price * Model.CartProductIDs.Where(productID => productID == x.ID).Count())</strong>
                            </li>
                        </ul>
                    </div>

                    <div class="col-lg-12">
                        <button id="printBtn" class="btn btn-primary"><i class="ico-printer"></i> Print</button>
                        <button id="pdfBtn" class="btn btn-info"><i class="ico-document-file-pdf"></i> PDF</button>
                    </div>

                </div>
            </div>
        </div>
    </div>
    
}
else
{
    <div id="main">
        <div class="main-holder">
            <div class="container" style="margin-top: 130px; margin-bottom: 30px;">
                <div class="heading-area">
                    <h2>Orderd Detail</h2>
                </div>
                <div class="text-center text-danger">
                    <p> No product in Cart.</p>
                </div>
            </div>
        </div>
    </div>
}
<script>
    $(document).ready(function () {
        var doc = new jsPDF();
        var specialElementHandlers = {
            '#editor': function (element, renderer) {
                return true;
            }
        };
        $("#printBtn").on("click", function () {
            window.print();
        });

        $("#pdfBtn").on("click", function () {
            doc.fromHTML($('#main').html(), 15, 15, {
                'width': 170,
                'elementHandlers': specialElementHandlers
            });
            doc.save('kuchB.pdf');

        });
    });
</script>

FurnitureApplication.web/Views/Shop1/FilterProducts.cshtml
@model FilterProductsViewModel
@{
    var DefaultimageUrl = "/images/empty-member.png";
 }
<div class="room-ideas">
    <div class="filter-shop">
        <p class="text-right">Showing @(((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize) + 1) - @(((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize ) + (Model.Products.Count < Model.Pager.PageSize ? Model.Products.Count : Model.Pager.PageSize)) of @Model.Pager.TotalItems Products</p>
    </div>
    <div class="row">
        @foreach (var product in Model.Products)
        {
            var imageUrl = string.IsNullOrEmpty(product.ImageUrl) ? DefaultimageUrl : product.ImageUrl;

            <div class="col-lg-4">
                <div class="card">
                    <div class="plan-ribbon-wrapper"><div class="plan-ribbon">Popular</div></div>
                    <img class="card-img-top" src="@imageUrl" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">@product.Name</h5>
                        <p class="card-text">@product.Description</p>
                        <span class="price-holder">$ @product.Price</span>
                        <ul class="card-action-icons">
                            <li><a href="#" data-id="@product.ID" class="ico-cart3 productAddToCart"></a></li>
                            <li><a href="#" class="ico-heart11"></a></li>
                            <li><a href="@Url.Action("Details", "Detail", new { ID = product.ID })" class="ico-eye9"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="text-center">
        @if (Model.Pager != null && Model.Pager.TotalPages > 1)
            {
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    @if (Model.Pager.CurrentPage > 1)
                    {
                        <li class="page-item">
                            <a class="PageDataLink page-link" data-href="@Url.Action("FilterProducts", "Shop1", new { pageNo = Model.Pager.CurrentPage - 1, sortBy = Model.SortBy, categoryID = Model.CategoryID})" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    }
                    @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                    {
                    string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                        <li class="page-item @activeClass"><a class="PageDataLink page-link" data-href="@Url.Action("FilterProducts", "Shop1", new { pageNo = page, sortBy = Model.SortBy, categoryID = Model.CategoryID})">@page</a></li>
                    }
                    @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                    {
                        <li class="page-item">
                            <a class="PageDataLink page-link" data-href="@Url.Action("FilterProducts", "Shop1", new { pageNo = Model.Pager.CurrentPage + 1, sortBy = Model.SortBy, categoryID = Model.CategoryID})" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    }
                </ul>
            </nav>
        }
    </div>
</div>
<input type="hidden" id="SearchTerm" value="@Model.SearchTerm" />
<input type="hidden" id="SortBy" value="@Model.SortBy" />
<input type="hidden" id="CategoryID" value="@Model.CategoryID" />
<script>
    $(".PageDataLink").click(function () {
        var url = $(this).attr("data-href");

        if (url != "" || url != undefined) {
            GetData(url);
        }
    });

    var products;
    $(".productAddToCart").click(function () {
        
        var existingCookieData = $.cookie("CartProducts");

        if (existingCookieData != undefined && existingCookieData != "" && existingCookieData!= null)
        {
            products = existingCookieData.split("-");
        }
        else {
            products = [];
        }
        var productID = $(this).attr("data-id");

        products.push(productID)

        $.cookie("CartProducts", products.join("-"), { path: "/" });

        updateCartProducts();

        swal("Done", "product added to cart!", "success");
    });
</script>













@*<div>
    @if (Model.Pager != null && Model.Pager.TotalPages > 1)
    {

        if (Model.Pager.CurrentPage > 1)
        {
            <button class="pageButtons" data-pageno="1">First</button>
            <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage - 1)">Previous</button>}

        for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
        {
            string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

            <button class="@activeClass pageButtons" data-pageno="@page">@page</button>}

        if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
        {
            <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage + 1)">Next</button>
            <button class="pageButtons" data-pageno="@Model.Pager.EndPage">Last</button>}
    }
</div>*@

FurnitureApplication.web/Views/Shop1/Index.cshtml
@using FurnitureApplication.web.code
@model ShopViewModel
@{
    ViewBag.Title = "Index";
}

<div id="main">
    <div class="main-holder">
        <div class="container" style="margin-top: 130px; margin-bottom: 30px;">
            <div class="heading-area">
                <h2>Products</h2>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="search-box" style="width: 100%;">
                        <form role="search" method="get" action="@Url.Action("Index", "Shop1")">
                            <div class="search-box" style="width:100%;">
                                <div class="search-row">
                                    <input class="form-control" id="searchTxt" type="search" value="@Model.SearchTerm" name="searchTerm" placeholder="Search" />
                                    <span onclick="action" id="searchBtn" class="ico-search10"></span>
                                </div>
                            </div>
                        </form>
                    </div>
                    <hr />
                    <div class="form-group">
                        <h5 class="widget-title">Sort By</h5>
                        <ul class="sortBy">
                            <li><a href="#" data-href="@Url.Action("FilterProducts", "Shop1", new { sortBy = (int)SortByEnums.Default, categoryID = Model.CategoryID })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnums.Default ? "active" : string.Empty : string.Empty)">Default - Newest</a></li>
                            <li><a href="#" data-href="@Url.Action("FilterProducts", "Shop1", new { sortBy = (int)SortByEnums.Popularity, categoryID = Model.CategoryID })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnums.Popularity ? "active" : string.Empty : string.Empty)">Popularity</a></li>
                            <li><a href="#" data-href="@Url.Action("FilterProducts", "Shop1", new { sortBy = (int)SortByEnums.PriceLowToHigh, categoryID = Model.CategoryID })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnums.PriceLowToHigh ? "active" : string.Empty : string.Empty)">Price: Low To High</a></li>
                            <li><a href="#" data-href="@Url.Action("FilterProducts", "Shop1", new { sortBy = (int)SortByEnums.PriceHighToLow, categoryID = Model.CategoryID })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnums.PriceHighToLow ? "active" : string.Empty : string.Empty)">Price: High To Low</a></li>
                        </ul>
                    </div>
                    <hr />
                    <div class="form-group clearfix">
                        <h5 class="widget-title">Filter Tags</h5>
                        <ul class="tag-list">
                            @foreach (var category in Model.FeaturedCategories)
                            {
                                <li><a class="dataLink btn btn-primary @(Model.CategoryID.HasValue && Model.CategoryID.Value == category.ID ? "active" : string.Empty)" data-href="@Url.Action("FilterProducts", "Shop1", new { categoryID = category.ID, sortBy = Model.SortBy})">@category.Name</a></li>
                            }
                        </ul>
                    </div>
                    <hr />
                    <div class="form-group clearfix">
                        <div class="widget widget-price">
                            <h5 class="widget-title">Filter by price</h5>
                            <div class="price-filter">
                                <div id="slide-range"></div>
                                <p class="amount">
                                    Price: <input type="text" id="amount" disabled="">
                                </p>
                            </div>
                        </div>
                    </div>
                    <a href="@Url.Action("Index", "Shop1")" class="btn btn-primary">Reset Filters</a>
                </div>
                <div class="col-lg-8">
                    <div id="ProductsDiv">
                        @{
                            var filterProductsViewModel = new FilterProductsViewModel();
                            filterProductsViewModel.Products = Model.Products;
                            filterProductsViewModel.Pager = Model.Pager;
                            filterProductsViewModel.CategoryID = Model.CategoryID;
                            filterProductsViewModel.SortBy = Model.SortBy;

                            Html.RenderPartial("FilterProducts", filterProductsViewModel);
                        }
                    </div>

                </div>
            </div>
            <hr />
        </div>
    </div>
</div>

<script>
    var callTimeout;

    var priceSlider = $( "#slide-range" ).slider({
        range: true,
        min: 0,
        max: @Model.MaximumPrice,
        values: [ 0, @Model.MaximumPrice ],
        slide: function( event, ui ) {
            var minPrice = ui.values[0];
            var maxPrice = ui.values[1];

            $("#amount").val("$" + minPrice + ".00" + "-" + "$" + maxPrice + ".00");
            clearTimeout(callTimeout);
            callTimeout = setTimeout(PriceRangeChange, 500);

        }
    });

    $(".dataLink").click(function(){
        var url = $(this).attr("data-href");
        if(url != "" || url != undefined){
            GetData(url);
        }
    });

    function GetData(durl){
        $.ajax({
            url: durl,
            data: {
                minimumPrice : priceSlider.slider("values", 0),
                maximumPrice : priceSlider.slider("values", 1)
            }
        })
        .done(function (response) {
            $("#ProductsDiv").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    }
    function PriceRangeChange(){
        $.ajax({
            url: '@Url.Action("FilterProducts", "Shop1")',
            data: {
                searchTerm: $("#SearchTerm").val(),
                sortBy: $("#SortBy").val(),
                categoryID: $("#CategoryID").val(),
                minimumPrice : priceSlider.slider("values", 0),
                maximumPrice : priceSlider.slider("values", 1)
            }
        })
        .done(function (response) {
            $("#ProductsDiv").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    }
</script>