FurnitureApplication.web/ViewModels/ProductViewModels.cs
using FurnitureApplication.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FurnitureApplication.web.ViewModels
{
    public class ProductSearchViewModel : BaseEntity
    {
        public List<Product> Products { get; set; }
        public string SearchTerm { get; set; }
        public Pager Pager { get; set; }
        public int PageNo { get; set; }
    }

    public class NewProductViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageUrl { get; set; }

        public List<Category> AvailableCategories { get; set; }
    }

    public class EditProductViewModel
    {
        public int ID { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public decimal OriginalPrice { get; set; }
        public bool HasDiscount { get; set; }
        public double DiscountPercentage { get; set; }
        public int CategoryID { get; set; }
        public string ImageUrl { get; set; }

        public List<Category> AvailableCategories { get; set; }
    }


    public class ProductViewModel
    {
        public Product Product { get; set; }
    }
}

FurnitureApplication.web/Controllers/CategoryController.cs
using FurnitureApplication.Entities;
using FurnitureApplication.Services;
using FurnitureApplication.web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace FurnitureApplication.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        // GET: Category
        [HttpGet]
        public ActionResult index()
        {
            var categries = CategoriesServices.Instance.GetCategories();

            return View(categries);
        }
        public ActionResult CategoryTable(string search, int? pageNo, bool asShared = false)
        {
            var pageSize = ConfigurationsService.Instance.PageSize();
            ViewBag.UseAsShared = asShared;
            CategorySearchViewModel model = new CategorySearchViewModel();
            model.SearchTerm = search;

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var totalRecords = CategoriesServices.Instance.GetCategoriesCount(search);
            model.Categories = CategoriesServices.Instance.GetCategories(search, pageNo.Value, pageSize);

            if (model.Categories != null)
            {
                model.Pager = new Pager(totalRecords, pageNo, pageSize);

                return PartialView(model);
            }
            else
            {
                return HttpNotFound();
            }
        }

        //*****************Create option

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(NewCategoryViewModel model)
        {
            var newCategory = new Category();
            newCategory.Name = model.Name;
            newCategory.Description = model.Description;
            newCategory.ImageUrl = model.ImageUrl;
            newCategory.IsFeatured = model.isFeatured;
            CategoriesServices.Instance.SaveCategory(newCategory);
            return RedirectToAction("index");
        }

        //*****************Edit option

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditCategoryViewModel model = new EditCategoryViewModel();

            var category = CategoriesServices.Instance.GetCategory(ID);

            model.ID = category.ID;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageUrl = category.ImageUrl;
            model.isFeatured = category.IsFeatured;

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel model)
        {
            var existingCategory = CategoriesServices.Instance.GetCategory(model.ID);
            existingCategory.Name = model.Name;
            existingCategory.Description = model.Description;
            existingCategory.ImageUrl = model.ImageUrl;
            existingCategory.IsFeatured = model.isFeatured;

            CategoriesServices.Instance.UpdateCategory(existingCategory);

            return new HttpStatusCodeResult(200);
        }


        //*****************Delete option

        [HttpGet]
        public ActionResult Delete(int ID)
        {
            var category = CategoriesServices.Instance.GetCategory(ID);
            return View(category);
        }

        [HttpPost]
        public ActionResult Delete(Category category)
        {
            category = CategoriesServices.Instance.GetCategory(category.ID);

            CategoriesServices.Instance.DeleteCategory(category.ID);
            return new HttpStatusCodeResult(200);
        }
    }
}

FurnitureApplication.web/Controllers/DetailController.cs
using FurnitureApplication.Services;
using FurnitureApplication.web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    public class DetailController : Controller
    {
        // GET: Detail
        [HttpGet]
        public ActionResult Details(int ID)
        {
            ProductViewModel model = new ProductViewModel();

            model.Product = ProductsServices.Instance.GetProduct(ID);

            return View(model);
        }
    }
}

FurnitureApplication.web/Controllers/ProductController.cs
using FurnitureApplication.Entities;
using FurnitureApplication.Services;
using FurnitureApplication.web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductTable(string search, int? pageNo = 1)
        {
            var pageSize = ConfigurationsService.Instance.PageSize();
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.SearchTerm = search;

            pageNo = pageNo.HasValue ? pageNo > 0 ? pageNo.Value : 1 : 1 ;

            var totalRecords = ProductsServices.Instance.GetProductsCount(search);
            model.Products = ProductsServices.Instance.GetProducts(search, pageNo.Value, pageSize);
            if(model.Products != null)
            {
                model.Pager = new Pager(totalRecords, pageNo, pageSize);
                return PartialView(model);
            }
            else
            {
                return HttpNotFound();
            }
            
        }

        //****************create Product
        [HttpGet]
        public ActionResult Create()
        {

            var categories = CategoriesServices.Instance.GetCategories();

            return PartialView(categories);
        }

        [HttpPost]
        public ActionResult Create(NewCategoryViewModel model)
        {

            var newProduct = new Product();
            newProduct.Name = model.Name;
            newProduct.Description = model.Description;
            newProduct.Price = model.Price;
            newProduct.DiscountPercentage = model.DiscountPercentage;
            newProduct.HasDiscount = model.HasDiscount;
            newProduct.OriginalPrice = model.OriginalPrice;

            if(newProduct.DiscountPercentage > 0)
            {
                newProduct.HasDiscount = true;
                var discountAmount = (decimal)(newProduct.DiscountPercentage / 100.0) * newProduct.OriginalPrice;
                newProduct.Price = newProduct.OriginalPrice - discountAmount;
            }


            newProduct.Category = CategoriesServices.Instance.GetCategory(model.CategoryID);
            newProduct.ImageUrl = model.ImageUrl;

            ProductsServices.Instance.SaveProduct(newProduct);

            return RedirectToAction("index");
        }

        //****************Edit Product

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();

            var product = ProductsServices.Instance.GetProduct(ID);

            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.ImageUrl = product.ImageUrl;

            model.DiscountPercentage = product.DiscountPercentage;
            model.HasDiscount = product.HasDiscount;
            model.OriginalPrice = product.OriginalPrice;

            model.AvailableCategories = CategoriesServices.Instance.GetAllCategories();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var existingProduct = ProductsServices.Instance.GetProduct(model.ID);
            existingProduct.Name = model.Name;
            existingProduct.Description = model.Description;
            existingProduct.Price = model.Price;

            existingProduct.DiscountPercentage = model.DiscountPercentage;
            existingProduct.HasDiscount = model.HasDiscount;
            existingProduct.OriginalPrice = model.OriginalPrice;

            if (model.HasDiscount && model.DiscountPercentage >= 0)
            {
                existingProduct.HasDiscount = true;
                var discountAmount = (decimal)(model.DiscountPercentage / 100.0) * model.OriginalPrice;
                existingProduct.Price = model.OriginalPrice - discountAmount;
            }else
            {
                existingProduct.HasDiscount = false;
                existingProduct.OriginalPrice = model.Price;
                existingProduct.DiscountPercentage = 0; 

            }

            existingProduct.Category = null; //mark it null. Because the referncy key is changed below
            existingProduct.CategoryID = model.CategoryID;

            //dont update imageURL if its empty
            if (!string.IsNullOrEmpty(model.ImageUrl))
            {
                existingProduct.ImageUrl = model.ImageUrl;
            }

            ProductsServices.Instance.UpdateProduct(existingProduct);

            return new HttpStatusCodeResult(200);
        }


        //**********Detail
        //[HttpGet]
        //public ActionResult Details(int ID)
        //{
        //    ProductViewModel model = new ProductViewModel();

        //    model.Product = ProductsServices.Instance.GetProduct(ID);

        //    return View(model);
        //}


        //****************delete Product

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductsServices.Instance.DeleteProduct(ID);
            
            return RedirectToAction("index");
        }

    }
}

FurnitureApplication.web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    public class SharedController : Controller
    {
        
        public JsonResult UploadImages()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("/images/shared/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageUrl = string.Format("/images/shared/{0}", fileName) };

                //var newImage = new Image() { NameValueCollectionExtensions = fileName };
                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageUrl = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { success = false, message = new HttpStatusCodeResult(500) };
                //}
            }
            catch(Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }
            return result;
        }
    }
}

FurnitureApplication.web/Controllers/WidgetsController.cs
using FurnitureApplication.Services;
using FurnitureApplication.web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    public class WidgetsController : Controller
    {
        // GET: Widgets
        public ActionResult Products(bool isLatestProducts, int? CategoryID = 0)
        {
            ProductsWidgetsViewModel model = new ProductsWidgetsViewModel();
            model.IsLatestProducts = isLatestProducts;

            if (isLatestProducts)
            {
                model.Products = ProductsServices.Instance.GetLatestProducts(4);
            }
            else if (CategoryID.HasValue && CategoryID.Value > 0)
            {
                model.Products = ProductsServices.Instance.GetProductsByCategory(CategoryID.Value, 4);
            }
            else
            {
                model.Products = ProductsServices.Instance.GetProducts(1, 8);
            }
            return PartialView(model);
        }
    }
}

FurnitureApplication.web/Views/Product/Edit.cshtml
@model EditProductViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

    var imageUrl = !string.IsNullOrEmpty(Model.ImageUrl) ? Model.ImageUrl : "/images/empty-member.png";
}

<hr />
<div id="main">
    <div class="main-holder">
        <div class="container" style="margin-top: 130px; margin-bottom: 30px;">
            <div class="heading-area">
                <h2>Edit Product</h2>
            </div>
            <form id="editProduct">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form">
                            <select class="form-control" name="CategoryID">
                                @foreach (var category in Model.AvailableCategories)
                                {
                                    var selected = category.ID == Model.CategoryID ? "selected" : string.Empty;
                                    <option value="@category.ID" @selected>@category.Name</option>
                                }
                            </select>


                            <div class="form-group">
                                <input type="hidden" name="ID" value="@Model.ID" />
                                <label>Name</label>
                                <input class="form-control" type="text" name="Name" placeholder="Name" value="@Model.Name" />
                            </div>
                            <div class="form-group">
                                <label>Sale Price</label>
                                <input class="form-control" type="number" id="Price" name="Price" placeholder="Price" required value="@Model.Price" />
                            </div>
                            <div class="custom-control custom-checkbox">
                                @Html.CheckBox("HasDiscount",Model.HasDiscount, new { @class="custom-control-input", id= "HasDiscount" })
                                @*<input type="checkbox" class="custom-control-input" id="HasDiscount" name="HasDiscount" />*@

                                <label class="custom-control-label" for="HasDiscount">Is On Discount? </label>
                            </div>
                            <div class="form-group discount-section" hidden>
                                <label>Original Price</label>
                                <input class="form-control" type="number" id="OriginalPrice" name="OriginalPrice" placeholder="Price" required  value="@Model.OriginalPrice"/>
                            </div>
                            <div class="form-group discount-section" hidden>
                                <label>Discount (%)</label>
                                <input class="form-control" type="number" id="DiscountPercentage" name="DiscountPercentage" placeholder="Price" min="0" max="100" value="@Model.DiscountPercentage" required />
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <input class="form-control" type="text" name="Description" placeholder="Description" value="@Model.Description" />
                            </div>
                            <div class="form-group">
                                <label>Image</label>
                                <input type="hidden" id="ImageUrl" name="ImageUrl" value="@Model.ImageUrl" />
                                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary" id="updateBtn" type="submit">Update</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <label>Image View</label>
                        <div class="Placeholder-img">
                            <img id="productImage" src="@imageUrl" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        setHasDisount();

        $("#HasDiscount").change(function () {
            setHasDisount();
        });

        function setHasDisount() {
            if ($("#HasDiscount").is(":checked")) {
                $(".discount-section").removeAttr("hidden");
                $(".discount-section").fadeIn();
                $("#Price").attr("disabled", "disabled");
            } else {
                $(".discount-section").fadeOut();
                $("#Price").removeAttr("disabled");
            }
        }

        $("#Price").change(function () {
            $("#OriginalPrice").val(this.value);
        });

        $("#OriginalPrice").change(function () {
            calculateDiscount();
        });

        $("#DiscountPercentage").change(function () {
            calculateDiscount();
        });

        function calculateDiscount() {
            var discount = $("#DiscountPercentage").val();
            var discountPercentage = Number.parseFloat(discount);
            var originalPrice = Number.parseFloat($("#OriginalPrice").val());
            var discountAmount = (discountPercentage / 100.0) * originalPrice;
            var price = originalPrice - discountAmount;

            $("#Price").val(price + "");
        }



    });// End of doucmnet ready
    $("#imageUpload").change(function () {
        var element = this;

        var formData = new FormData();

        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
        .done(function (response) {
            console.log(response);

            if (response.Success) {
                $("#ImageUrl").val(response.ImageUrl);
                $("#productImage").attr("src", response.ImageUrl);
            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            console.log(errorThrown);
            console.log();
            console.log(textStatus);

        });
    });
    $("#updateBtn").click(function (ev) {
        ev.preventDefault();
        $.ajax({
            type: 'POST',
            url: "/Product/Edit",
            data: $("#editProduct").serialize()
        })
        .done(function (response) {
            window.location.href = "/Product/Index";
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            //alert("Fail")
        });
    });
    function focussAction() {
        $("html, body").animate({
            scrollTop: $("#actionContainer").offset().top - 100
        }, 1000);
    }
</script>

FurnitureApplication.web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div id="main">
    <div class="main-holder">
        <div class="container" style="margin-top: 130px; margin-bottom: 30px;">
            <div class="heading-area">
                <h2>Products</h2>
            </div>
            <div id="tableContainer">
                @{
                    Html.RenderAction("ProductTable");
                }
            </div>
            <div id="actionContainer">

            </div>
        </div>
    </div>
</div>

FurnitureApplication.web/Views/Product/ProductTable.cshtml
@model ProductSearchViewModel
@{
    ViewBag.Title = "ProductTable";
}

<form method="post">
    <div style="margin-bottom: 30px; overflow: hidden;">
        <div class="col-lg-6 float-right">
            <button class="btn btn-primary float-right" type="button" onclick="location.href='@Url.Action("Create")'" id="newBtn">New Product</button>
        </div>
        <div class="col-lg-6 float-left">
            <div class="search-box create-page">
                <div class="search-row">
                    <input class="form-control" id="searchTxt" type="text" name="Search" value="@Model.SearchTerm" placeholder="Search" />
                    <span onclick="action" id="searchBtn" class="ico-search10"></span>
                </div>
            </div>
        </div>
    </div>
</form>
<div>
    <table class="table table-hover" id="ProductsTable">
        <thead>
            <tr>
                <th scope="col">Product Name</th>
                <th scope="col">Category</th>
                <th scope="col">Price</th>
                <th scope="col">Description</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null && Model.Products.Count > 0)
            {
                foreach (var product in Model.Products)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>
                            @if (product.Category != null)
                            {
                                <text>@product.Category.Name</text>
                            }
                            else
                            {
                                <span>-</span>
                            }
                        </td>
                        <td>@product.Price</td>
                        <td><div class="description ellipsis">@product.Description</div></td>
                        <td>
                            <button class="action ico-pencil5" onclick="location.href='@Url.Action("Edit", "Product" , new RouteValueDictionary(new { id = product.ID }))'" data-id="@product.ID"></button>
                            <button class="action ico-trash-can deleteBtn" data-id="@product.ID"></button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td class="text-center text-danger" colspan="5">No Product found</td>
                </tr>
            }
        </tbody>
    </table>
    <div>
        @if (Model.Pager != null && Model.Pager.TotalPages > 1)
        {

            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageno="1">First</button>
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage - 1)">Previous</button>}

            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <button class="@activeClass pageButtons" data-pageno="@page">@page</button>}

            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage + 1)">Next</button>
                <button class="pageButtons" data-pageno="@Model.Pager.EndPage">Last</button>}
        }
    </div>
</div>
<script>
    //$('#ProductsTable').DataTable();

    $(".pageButtons").click(function () {
        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")',
            data: {
                pageNo: $(this).attr("data-pageNo"),
                search: '@Model.SearchTerm'
            }
        })
        .done(function (response) {
            $("#tableContiner").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });

    $(".page-link").click(function () {
        $.ajax({
            url: "/Product/ProductTable",
            data: {
                pageNo : $(this).attr("data-pageNo")
            }
        })
        .done(function (response) {
            $("#tableContainer").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail")
        });
    });

    $("#searchBtn").click(function (ev) {
        ev.preventDefault();
        var searchValue = $("#searchTxt").val();

        $.ajax({
            url: '@Url.Action("ProductTable", "Product")',
            data: {
                search: searchValue
            }
        })
        .done(function (response) {
            $("#ProductsTable").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail")
        });
    });

    $("#newBtn").click(function () {
        $.ajax({
            url: "/Product/Create",
        })
        .done(function (response) {
            $("#actionContainer").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail")
        });
    });


    $(".deleteBtn").click(function () {
        swal({
            title: "Are tou sure you want to delete this product?",
            text: "Once deleted, you will not be able to recover this imaginary product!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {

                $.ajax({
                    type: "POST",
                    url: "/Product/Delete",
                    data: {
                        ID: $(this).attr("data-id")
                    }
                })
                .done(function (response) {
                    window.location.reload(false);
                    //$("html").html(response);
                    //$("#tableContainer").html(response);

                    swal("Record deleted successfully!", {
                        icon: "success",
                    });
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Fail")
                });
            }
            else {
                swal("Your imaginary file is safe!");
            }
        });
    });
    var products = [];

    $(".addToCart").click(function () {

        var productID = $(this).attr("data-id");

        products.push(productID)

        $.cookie("CartProducts", products.join("-"), { path: "/"});

        alert("add to cart added");
    });

    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");
    })

    function focussAction() {
        $("html, body").animate({
            scrollTop: $("#actionContainer").offset().top - 100
        }, 1000);
    }
</script>