FurnitureApplication.web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

FurnitureApplication.web/Controllers/OrderController.cs
using System;
using FurnitureApplication.Services;
using FurnitureApplication.web.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Order
        public ActionResult Index(string userID, string status, int? pageNo)
        {
            OrdersViewModel model = new OrdersViewModel();
            model.UserID = userID;
            model.Status = status;

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            var pageSize = ConfigurationsService.Instance.PageSize();

            model.Orders = OrdersService.Instance.SearchOrders(userID, status, pageNo.Value, pageSize);
            var totalRecords = OrdersService.Instance.SearchOrdersCount(userID, status);

            model.Pager = new Pager(totalRecords, pageNo, pageSize);

            return View(model);
        }

        public ActionResult Details(int ID)
        {
            OrderDetailsViewModel model = new OrderDetailsViewModel();

            model.Order = OrdersService.Instance.GetOrderByID(ID);

            if (model.Order != null)
            {
                model.OrderBy = UserManager.FindById(model.Order.UserID);
            }

            model.AvailableStatuses = new List<string>() { "Pending", "In Progress", "Delivered" };

            return View(model);
        }

        public JsonResult ChangeStatus(string status, int ID)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            result.Data = new { Success = OrdersService.Instance.UpdateOrderStatus(ID, status) };

            return result;
        }
    }
}

FurnitureApplication.web/Controllers/ProductController.cs
using FurnitureApplication.Entities;
using FurnitureApplication.Services;
using FurnitureApplication.web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductTable(string search, int? pageNo = 1)
        {
            var pageSize = ConfigurationsService.Instance.PageSize();
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.SearchTerm = search;

            pageNo = pageNo.HasValue ? pageNo > 0 ? pageNo.Value : 1 : 1 ;

            var totalRecords = ProductsServices.Instance.GetProductsCount(search);
            model.Products = ProductsServices.Instance.GetProducts(search, pageNo.Value, pageSize);
            if(model.Products != null)
            {
                model.Pager = new Pager(totalRecords, pageNo, pageSize);
                return PartialView(model);
            }
            else
            {
                return HttpNotFound();
            }
            
        }

        //****************create Product
        [HttpGet]
        public ActionResult Create()
        {

            var categories = CategoriesServices.Instance.GetCategories();

            return PartialView(categories);
        }

        [HttpPost]
        public ActionResult Create(NewCategoryViewModel model)
        {

            var newProduct = new Product();
            newProduct.Name = model.Name;
            newProduct.Description = model.Description;
            newProduct.Price = model.Price;
            newProduct.DiscountPercentage = model.DiscountPercentage;
            newProduct.HasDiscount = model.HasDiscount;
            newProduct.OriginalPrice = model.OriginalPrice;

            if(newProduct.DiscountPercentage > 0)
            {
                newProduct.HasDiscount = true;
                var discountAmount = (decimal)(newProduct.DiscountPercentage / 100.0) * newProduct.OriginalPrice;
                newProduct.Price = newProduct.OriginalPrice - discountAmount;
            }


            newProduct.Category = CategoriesServices.Instance.GetCategory(model.CategoryID);
            newProduct.ImageUrl = model.ImageUrl;

            ProductsServices.Instance.SaveProduct(newProduct);

            return RedirectToAction("index");
        }

        //****************Edit Product

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();

            var product = ProductsServices.Instance.GetProduct(ID);

            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.ImageUrl = product.ImageUrl;

            model.DiscountPercentage = product.DiscountPercentage;
            model.HasDiscount = product.HasDiscount;
            model.OriginalPrice = product.OriginalPrice;

            model.AvailableCategories = CategoriesServices.Instance.GetAllCategories();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var existingProduct = ProductsServices.Instance.GetProduct(model.ID);
            existingProduct.Name = model.Name;
            existingProduct.Description = model.Description;
            existingProduct.Price = model.Price;

            existingProduct.DiscountPercentage = model.DiscountPercentage;
            existingProduct.HasDiscount = model.HasDiscount;
            existingProduct.OriginalPrice = model.OriginalPrice;

            if (model.HasDiscount && model.DiscountPercentage >= 0)
            {
                existingProduct.HasDiscount = true;
                var discountAmount = (decimal)(model.DiscountPercentage / 100.0) * model.OriginalPrice;
                existingProduct.Price = model.OriginalPrice - discountAmount;
            }else
            {
                existingProduct.HasDiscount = false;
                existingProduct.OriginalPrice = model.Price;
                existingProduct.DiscountPercentage = 0; 

            }

            existingProduct.Category = null; //mark it null. Because the referncy key is changed below
            existingProduct.CategoryID = model.CategoryID;

            //dont update imageURL if its empty
            if (!string.IsNullOrEmpty(model.ImageUrl))
            {
                existingProduct.ImageUrl = model.ImageUrl;
            }

            ProductsServices.Instance.UpdateProduct(existingProduct);

            return new HttpStatusCodeResult(200);
        }


        //**********Detail
        //[HttpGet]
        //public ActionResult Details(int ID)
        //{
        //    ProductViewModel model = new ProductViewModel();

        //    model.Product = ProductsServices.Instance.GetProduct(ID);

        //    return View(model);
        //}


        //****************delete Product

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductsServices.Instance.DeleteProduct(ID);
            
            return RedirectToAction("index");
        }

    }
}

FurnitureApplication.web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    public class SharedController : Controller
    {
        
        public JsonResult UploadImages()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("/images/shared/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageUrl = string.Format("/images/shared/{0}", fileName) };

                //var newImage = new Image() { NameValueCollectionExtensions = fileName };
                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageUrl = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { success = false, message = new HttpStatusCodeResult(500) };
                //}
            }
            catch(Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }
            return result;
        }
    }
}

FurnitureApplication.web/Controllers/Shop1Controller.cs
using FurnitureApplication.Entities;
using FurnitureApplication.Services;
using FurnitureApplication.web.Models;
using FurnitureApplication.web.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace FurnitureApplication.web.Controllers
{
    public class Shop1Controller : Controller
    {


        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult CheckoutDetail()
        {
            CheckoutViewModel model = new CheckoutViewModel();

            var CartProductsCookie = Request.Cookies["CartProducts"];

            if (CartProductsCookie != null && !string.IsNullOrEmpty(CartProductsCookie.Value))
            {
                model.CartProductIDs = CartProductsCookie.Value.Split('-').Select(x => int.Parse(x)).ToList();

                model.CartProducts = ProductsServices.Instance.GetProducts(model.CartProductIDs);

                model.User = UserManager.FindById(User.Identity.GetUserId());

            }

            return View(model);
        }
        public ActionResult Index(string searchTerm, int? minimumPrice, int? maximumPrice, int? categoryID, int? sortBy, int? pageNo)
        {
            var pageSize = ConfigurationsService.Instance.ShopPageSize();

            ShopViewModel model = new ShopViewModel();
            model.SearchTerm = searchTerm;
            model.FeaturedCategories = CategoriesServices.Instance.GetFeaturedCategories();
            model.MaximumPrice = ProductsServices.Instance.GetMaximumPrice();

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.SortBy = sortBy;
            model.CategoryID = categoryID;

            int totalCount = ProductsServices.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy);
            model.Products = ProductsServices.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy, pageNo.Value, pageSize);
            
            model.Pager = new Pager(totalCount, pageNo, pageSize);
            return View(model);

        }
        public ActionResult FilterProducts(string searchTerm, int? minimumPrice, int? maximumPrice, int? categoryID, int? sortBy, int? pageNo)
        {
            var pageSize = ConfigurationsService.Instance.ShopPageSize();

            FilterProductsViewModel model = new FilterProductsViewModel();
            model.SearchTerm = searchTerm;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.SortBy = sortBy;
            model.CategoryID = categoryID;

            int totalCount = ProductsServices.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy);
            model.Products = ProductsServices.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy, pageNo.Value, pageSize);
            

            model.Pager = new Pager(totalCount, pageNo, pageSize);

            return PartialView(model);
        }
        [Authorize]
        public ActionResult Checkout()
        {
            CheckoutViewModel model = new CheckoutViewModel();

            var CartProductsCookie = Request.Cookies["CartProducts"];

            if(CartProductsCookie != null && !string.IsNullOrEmpty(CartProductsCookie.Value))
            {
                model.CartProductIDs = CartProductsCookie.Value.Split('-').Select(x => int.Parse(x)).ToList();

                model.CartProducts = ProductsServices.Instance.GetProducts(model.CartProductIDs);

                model.User = UserManager.FindById(User.Identity.GetUserId());

            }

            return View(model);
        }
        public JsonResult PlaceOrder(CheckoutViewModel model, string productIDs)
        {
            model.User = UserManager.FindById(User.Identity.GetUserId());
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            if (!string.IsNullOrEmpty(productIDs))
            {
                var productQuantities = productIDs.Split('-').Select(x => int.Parse(x)).ToList();
                var boughtProducts = ProductsServices.Instance.GetProducts(productQuantities.Distinct().ToList());

                Order newOrder = new Order();
                newOrder.UserID = User.Identity.GetUserId();
                newOrder.orderedAt = DateTime.Now;
                newOrder.status = "Pending";
                newOrder.TotalAmount = boughtProducts.Sum(x => x.Price * productQuantities.Where(productID => productID == x.ID).Count());

                newOrder.OrderItems = new List<OrderItem>();
                newOrder.OrderItems.AddRange(boughtProducts.Select(x => new OrderItem() { ProductID = x.ID, Quantity = productQuantities.Where(productID => productID == x.ID).Count() }));

           
                var rowsEffected = ShopService.Instance.SaveOrder(newOrder);
                result.Data = new { Success = true, Rows = rowsEffected };

                //*********Email sending code

                var fromEmail = new MailAddress("rastgroup1@gmail.com", "Rast Group");
                var toEmail = new MailAddress(model.User.Email);
                var fromEmailPassword = "ayaz123456"; //replace with actual Password

                string subject = "Order";
                string body = "Your Order Placed successfully";
                
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
                };
                using (var message = new MailMessage(fromEmail, toEmail)
                {

                    Subject = subject,
                    Body = body,
                    IsBodyHtml = true
                })
                    smtp.Send(message);
            }
            else
            {
                result.Data = new { Success = false };
            }
            return result;
        }
    }
}

FurnitureApplication.web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Rast Furniture</title>
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/bootstrap-reboot.min.css")
    @Styles.Render("~/Content/bootstrap-grid.min.css")
    @Styles.Render("~/Content/jquery.dataTables.min.css")
    @Styles.Render("~/Content/jquery-ui.css")
    @Styles.Render("~/Content/jquery-ui.css")
    @Styles.Render("~/Content/all.css")
    @Styles.Render("~/Content/shortcodes.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/popper.min.js")
    @Scripts.Render("~/Scripts/jquery-1.11.2.min.js")
    @Scripts.Render("~/Scripts/jquery.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/jquery.cookie.js")
    @Scripts.Render("~/Scripts/sweetalert.min.js")
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/jquery-ui.js")
    @Scripts.Render("~/Scripts/jquery.isotope.min.js")
    @Scripts.Render("~/Scripts/main.js")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.4.1/jspdf.debug.js" integrity="sha384-THVO/sM0mFD9h7dfSndI6TS0PgAGavwKvB5hAxRRvc0o9cPLohB0wb/PTA7LdUHs" crossorigin="anonymous"></script>
    

</head>
<body>
    <div id="wrapper">
        <div id="header">
            <div class="container">
                <div class="top-header">
                    <div class="float-right">
                        @*<div class="header-icon-links">
                            <a href="#">
                                <span class="number">2</span>
                                <span class="ico-heart11"></span>
                            </a>
                        </div>*@
                        <div class="header-icon-links">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a href="#" >@User.Identity.Name</a>
                            }
                        </div>
                        <div class="header-icon-links">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a href="@Url.Action("Checkout", "Shop1")">
                                    <span class="number" id="cartProductsCount">0</span>
                                    <span class="ico-cart3"></span>
                                </a>
                            }
                            else
                            {
                                <a href="@Url.Action("Checkout", "Shop1")">
                                    <span class="number">0</span>
                                    <span class="ico-cart3"></span>
                                </a>
                            }

                        </div>
                    </div>
                    @*<div class="search-box float-left">
                        <div class="search-row">
                            <input type="text" placeholder="Search" />
                            <span class="ico-search10"></span>
                        </div>
                    </div>*@
                </div>
                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="logo">
                        <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img src="../../images/rast-furniture-logo.png"></a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Shop1")">Shop</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Checkout", "Shop1")">Checkout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "OrderHistory")">Orders History</a>
                            </li>
                            <li class="nav-item sign-in">
                                @{
                                    if (Request.IsAuthenticated)
                                    {
                                        <a class="nav-link" href="/account/logoff">Logout</a>
                                    }
                                    else
                                    {
                                        <a class="nav-link" href="/account/login">LogIn</a>
                                    }
                                }
                            </li>
                            
                        </ul>
                        
                    </div>
                </nav>
            </div>
        </div>
        @RenderBody()
    </div>
    <div id="footer">
        <div class="footer-bottom">
            <div class="container">
                <p>© Powered by Rast</p>
                <ul class="social-links">
                    
                    <li><a href="#" class="ico-twitter4"></a></li>
                    <li><a href="#" class="ico-googleplus"></a></li>
                    <li><a href="#" class="ico-linkedin5"></a></li>
                </ul>

            </div>
        </div>
    </div>
    @RenderSection("scripts", required: false)
    <script>
        function updateCartProducts() {
            var cartProducts;
            var existingCookieData = $.cookie('CartProducts');

            if (existingCookieData != undefined && existingCookieData != "" && existingCookieData != null) {
                cartProducts = existingCookieData.split('-');
            }
            else {
                cartProducts = [];
            }
            $('#cartProductsCount').html(cartProducts.length);
        };
        updateCartProducts();
    </script>
</body>
</html>

FurnitureApplication.web/Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Rast Furniture - @ViewBag.Title </title>
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/bootstrap-reboot.min.css")
    @Styles.Render("~/Content/bootstrap-grid.min.css")
    @Styles.Render("~/Content/jquery.dataTables.min.css")
    @Styles.Render("~/Content/jquery-ui.css")
    @Styles.Render("~/Content/all.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/popper.min.js")
    @Scripts.Render("~/Scripts/jquery-1.11.2.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/jquery.min.js")
    @Scripts.Render("~/Scripts/jquery.cookie.js")
    @Scripts.Render("~/Scripts/sweetalert.min.js")
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/jquery-ui.js")
    @Scripts.Render("~/Scripts/main.js")
    
    
</head>
<body>
    <div id="wrapper">
        <div id="header">
            <div class="container">
                <div class="top-header">
                    <div class="float-right">
                        <div class="header-icon-links">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a href="#" >@User.Identity.Name</a>
                            }
                        </div>
                    </div>
                </div>
                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="logo">
                        <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img src="../../images/rast-furniture-logo.png"></a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="@Url.Action("Index", "Admin")">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Product")">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Category")">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Order")">Orders</a>
                            </li>
                            <li class="nav-item sign-in">
                                @{
                                    if (Request.IsAuthenticated)
                                    {
                                        <a class="nav-link" href="/account/logoff">Logout</a>
                                    }
                                    else
                                    {
                                        <a class="nav-link" href="/account/login">LogIn</a>
                                    }

                                }
                            </li>
                        </ul>
                        
                    </div>
                </nav>
            </div>
        </div>
        @RenderBody()
    </div>
    <div id="footer">
        <div class="footer-bottom">
            <div class="container">
                <p>© Powered by Rast</p>
                <ul class="social-links">
                    <li><a href="@ConfigurationsService.Instance.GetConfig("FacebookURL").value" class="ico-facebook5"></a></li>
                    <li><a href="#" class="ico-twitter4"></a></li>
                    <li><a href="#" class="ico-googleplus"></a></li>
                    <li><a href="#" class="ico-linkedin5"></a></li>
                </ul>

            </div>
        </div>
    </div>
    @RenderSection("scripts", required: false)
    <script>
        function updateCartProducts() {
            var cartProducts;
            var existingCookieData = $.cookie('CartProducts');

            if (existingCookieData != undefined && existingCookieData != "" && existingCookieData != null) {
                cartProducts = existingCookieData.split('-');
            }
            else {
                cartProducts = [];
            }
            $('#cartProductsCount').html(cartProducts.length);
        };
        updateCartProducts();
    </script>
</body>
</html>